INSERT INTO student (name, groupnumber, birthday) VALUES ('John', 1, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Chris', 1, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Carl', 1, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Oliver', 2, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('James', 2, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Lucas', 2, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Henry', 2, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Jacob', 3, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Logan', 3, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Mary', 4, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Anna', 5, CURRENT_DATE);
INSERT INTO student (name, groupnumber, birthday) VALUES ('Kate', 5, CURRENT_DATE);
insert into Subject (name, description, grade) VALUES ('Art', 'Art description', 1);
insert into Subject (name, description, grade) VALUES ('Music', 'Music description', 1);
insert into Subject (name, description, grade) VALUES ('Geography', 'Geography description', 2);
insert into Subject (name, description, grade) VALUES ('History', 'History description', 2);
insert into Subject (name, description, grade) VALUES ('PE', 'PE description', 3);
insert into Subject (name, description, grade) VALUES ('Math', 'Math description', 3);
insert into Subject (name, description, grade) VALUES ('Science', 'Science description', 4);
insert into Subject (name, description, grade) VALUES ('IT', 'IT description', 4);
insert into Subject (name, description, grade) VALUES ('Medicine', 'Medicine description', 5);
insert into Subject (name, description, grade) VALUES ('Law', 'Law description', 5);
INSERT INTO paymenttype (name)VALUES ('DAILY');
INSERT INTO paymenttype (name)VALUES ('WEEKLY');
INSERT INTO paymenttype (name)VALUES ('MONTHLY');
INSERT INTO payment (student_id, type_id, amount, payment_date) VALUES ( SELECT id FROM student WHERE name = 'John', SELECT id FROM paymenttype WHERE name = 'WEEKLY', 5015.45, '2023-01-01 08:10:00');
INSERT INTO payment (student_id, type_id, amount, payment_date) VALUES ( SELECT id FROM student WHERE name = 'Oliver', SELECT id FROM paymenttype WHERE name = 'MONTHLY', 6015.45, '2023-01-02 09:10:00');
INSERT INTO payment (student_id, type_id, amount, payment_date) VALUES ( SELECT id FROM student WHERE name = 'Henry', SELECT id FROM paymenttype WHERE name = 'WEEKLY', 5115.45, '2023-01-03 11:10:00');
INSERT INTO payment (student_id, type_id, amount, payment_date) VALUES ( SELECT id FROM student WHERE name = 'James', SELECT id FROM paymenttype WHERE name = 'DAILY', 7015.45, '2023-01-04 12:10:00');
INSERT INTO payment (student_id, type_id, amount, payment_date) VALUES ( SELECT id FROM student WHERE name = 'Anna', SELECT id FROM paymenttype WHERE name = 'WEEKLY', 4015.45, '2023-01-05 13:10:00');
INSERT INTO payment (student_id, type_id, amount, payment_date) VALUES ( SELECT id FROM student WHERE name = 'Kate', SELECT id FROM paymenttype WHERE name = 'MONTHLY', 8015.45, '2023-01-06 14:10:00');
insert into MARK (student_id, subject_id, mark) VALUES ( select id from Student where name = 'Chris', select id from Subject where name = 'Art', 8);
INSERT INTO mark (student_id, subject_id, mark) VALUES ( select id from Student where name = 'Oliver', select id from subject where name = 'History', 5);
INSERT INTO mark (student_id, subject_id, mark) VALUES ( select id from Student where name = 'James', select id from subject where name = 'Geography', 9);
INSERT INTO mark (student_id, subject_id, mark) VALUES ( select id from Student where name = 'Jacob', select id from subject where name = 'Math', 4);
INSERT INTO mark (student_id, subject_id, mark) VALUES ( select id from Student where name = 'Logan', select id from subject where name = 'PE', 9);
INSERT INTO mark (student_id, subject_id, mark) VALUES ( select id from Student where name = 'Mary', select id from subject where name = 'IT', 9);
INSERT INTO mark (student_id, subject_id, mark) VALUES ( select id from Student where name = 'Kate', select id from subject where name = 'Law', 8);
